### ISSUE TITLE
glutin fix breaks font rendering on OSX

### ISSUE THREAD

**Issue by dylanhart** [Vinatorul/minesweeper-rs#20]
commit 7b45d2b3f56aadb50f4c3e9e6ecce8a02ae30ff6 causes the following:

![bad font](https://cloud.githubusercontent.com/assets/1836899/9650848/7b238d88-51bd-11e5-92a7-6141d819f484.png)

note: this is on a branch of mine that has made some edits that are unrelated

**Comment by Vinatorul** [comment]
Can you, please, try to change `OpenGL::V3_2` to `OpenGL::V2_1`? I will add it as command line setting when come home.

**Comment by dylanhart** [comment]
V3_2 works
