### ISSUE TITLE
bug - Compiling piston-gfx_texture v0.2.0

### ISSUE THREAD

**Issue by ScottHuangZL** [Vinatorul/minesweeper-rs#27]
I am using Rust 1.4 nightly, win7 64bit.
======below are the compiler error info, please help on it, thanks. ==========

   Compiling piston-gfx_texture v0.2.0
error: internal compiler errorthread 'rustc' panicked at 'no entry found for key', ../src/libcore\option.rs:332

: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
Could not compile `piston-gfx_texture`.

To learn more, run the command again with --verbose.
[Finished in 1.0s]

**Comment by Vinatorul** [comment]
Thank you for your report. 
I know about this bug. I've opened issue in `gfx_texture` https://github.com/PistonDevelopers/gfx_texture/issues/67, and there also several issues at `rust` about this ICE.

**Comment by dobrite** [comment]
Should be fixed with Sep 6th's nightly: `rustc 1.4.0-nightly (f84d53ca0 2015-09-06)` ! :beers:

**Comment by Vinatorul** [comment]
Thank you kindly! 
Travis build passed: https://travis-ci.org/Vinatorul/minesweeper-rs/jobs/78816691

**Comment by ScottHuangZL** [comment]
Thank you, I will try it later.
