### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by MagaTailor** [Vinatorul/minesweeper-rs#43]
Hi,
It seems updating wayland dependencies might be required to work around this [issue](https://github.com/rust-lang/rust/issues/29867).

The versions from `Cargo.toml` are affected whereas master seems to compile cleanly on ARM.

**Comment by Vinatorul** [comment]
Thank you! I am going to make an update in few minutes.

**Comment by MagaTailor** [comment]
Thx, once wayland compiles it'll become clear if other crates are still not fixed. 

-original message-
Subject: Re: [minesweeper-rs] Dependencies update (#43)
From: Alexander Kuvaev notifications@github.com
Date: 05.01.2016 12:24

Thank you! I am going to make an update in few minutes.

---

**Comment by Vinatorul** [comment]
`wayland-sys v0.5.5` fails on nighly

**Comment by MagaTailor** [comment]
Thx; is there a tool to do that recursively?

**Comment by Vinatorul** [comment]
@petevine what do you mean under `recursively`? I've checked versions on `crates.io` then used `cargo update`.
There is [cargo oudated](https://github.com/kbknapp/cargo-outdated), but I fogot to use that (:

**Comment by MagaTailor** [comment]
Recursively meaning if you update one dependency that depends on other updated crates, they would get updated too :) 

For some `"*"` dependencies, `cargo update` can lead to a broken result.

**Comment by Vinatorul** [comment]
> Recursively meaning if you update one dependency that depends on other updated crates, they would get updated too :)

As I know cargo works so (check diff of my `Cargo.lock` file from the last pull request).

> For some "*" dependencies, cargo update can lead to a broken result.

I think this is rather rare for libs with >100 downloads. Wildcards nice for fast developing, but not for release, and I think anyone who will see them in `Cargo.toml` -  will make a PR to fix it.

**Comment by MagaTailor** [comment]
One last nag - `wayland-client` required fixing on ARM so it needs to be bumped to `0.5.8` again.

**EDIT**
You had better wait until I actually manage to build `minesweeper` again. There's still at least `freetype-rs` and `glutin` to fix.

**Comment by MagaTailor** [comment]
After bumping glutin to `0.5.8` and a cargo update, it compiles again.
